interval_minutes: 5
data_directory: .dist/data
node_id: node-a
node_name: Server A
peer_refresh_seconds: 60
monitor_dns:
  enabled: true
  target: 1.1.1.1
  interval_seconds: 60
  timeout_seconds: 4
targets:
  - id: tsunamibot
    name: Tsunami Bot
    service: tsunamibot.service
    timeout_seconds: 8
  - id: nginx
    name: Reverse Proxy
    service: nginx.service
    timeout_seconds: 5
peers:
  - id: node-b
    name: Server B
    base_url: http://192.168.55.120:8080
    enabled: true
